[dev]
framework = "#static"
command = "npm run dev"

[build]
command = "npm run build"
publish = "_site"

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1"